# -*- coding: utf-8 -*-
"""rearrange_string

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dsu1AsHZmlLREMi99kIw3t1_x3w6VtN5
"""

import random

text = input("Enter a string: ")

letters = list(text)
random.shuffle(letters)

shuffled_text = ''.join(letters)

print("Randomly rearranged string:", shuffled_text)